# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "remix-app-1"
client_id = "2053f512554446b2e245c0da06499e34"
application_url = "https://earlier-pontiac-grand-topics.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://earlier-pontiac-grand-topics.trycloudflare.com/auth/callback",
  "https://earlier-pontiac-grand-topics.trycloudflare.com/auth/shopify/callback",
  "https://earlier-pontiac-grand-topics.trycloudflare.com/api/auth/callback",
  "https://earlier-pontiac-grand-topics.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-5af2531c.myshopify.com"
